### ISSUE TITLE
spanner: sql question

### ISSUE THREAD

**Issue by dentiny** [googleapis/google-cloud-go#7265]
**Client**

Spanner client SDK v1.41.0

**Environment**

```
$ uname -a
Linux <hostname> 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Go Environment**

$ go version
go version go1.17.5 linux/amd64

**Code**

e.g.
```
stmt := spanner.Statement{
SQL: `
SELECT tableA.config_name, tableA.policy,
FROM tableA, tableB
WHERE tableA.config_name = tableB.config_name
AND tableA.owner = "name"
ORDER BY tableA.config_name ASC`
```

Schema:
```
CREATE TABLE tableA (
  config_name      STRING(MAX) NOT NULL,
  policy           BYTES(MAX),
) PRIMARY KEY (config_name);

CREATE TABLE tableB (
  config_name      STRING(MAX) NOT NULL,
  owner            STRING(MAX) NOT NULL,
) PRIMARY KEY (config_name, owner),
# Interleaved table to store tables physically together and improve transaction performance.
INTERLEAVE IN PARENT tableA ON DELETE CASCADE;

SELECT tableA.config_name, tableA.policy,
FROM tableA, tableB
WHERE tableA.config_name = tableB.config_name
AND tableB.owner = "name"
ORDER BY tableA.config_name ASC
```

**Expected behavior**

I expect the SQL to work, since I tried it in spanner cloud SQL console, and it works fine.

**Actual behavior**

Received error message
```
spanner: code = "InvalidArgument", desc = "bad query:
```

**Comment by dentiny** [comment]
Any progress on this issue?

**Comment by rahul2393** [comment]
Hello @dentiny, thanks for opening the issue, I tried replicating the issue but was not able to replicate. Below are my observation.
1) Query is actually invalid there is no column owner in `tableA`
2) Please make sure you use the latest version of "cloud.google.com/go/spanner" v1.43.0, v1.7.0 is very old.

Code used for replication https://go.dev/play/p/R20E1qDEvEk. Please share the code snippet which is causing the issue to help you better.

**Comment by dentiny** [comment]
> Code used for replication https://go.dev/play/p/R20E1qDEvEk. Please share the code snippet which is causing the issue to help you better.

The playback you linked shows "Go build failed."?

**Comment by rahul2393** [comment]
It will fail in playground because playground does not support third-party imports, please copy the code on your local machine and make sure dbPath is correct
replace
```
	db := "projects/my-project/instances/my-instance/databases/my-database"
```
and GOOGLE_APPLICATION_CREDENTIALS is correctly set with service_account json having access to project

**Comment by dentiny** [comment]
@rahul2393 I apology for my typo: have to make a similar SQL query from our internal project.

Clarification: I have updated the SQL query, and upgraded the spanner version to v1.41.0, still getting the issue.

**Comment by rahul2393** [comment]
>Clarification: I have updated the SQL query, and upgraded the spanner version to v1.41.0, still getting the issue.
Can you please share the snippet to replicate, I tried running the exact query and its returning the rows fine.
<img width="1764" alt="Screenshot 2023-01-21 at 11 56 06 AM" src="https://user-images.githubusercontent.com/18293335/213846848-bdc30286-e63b-49c6-985c-54eabb8322d3.png">

**Comment by dentiny** [comment]
Hi, I tried to upgrade spanner library, but met an issue.
```
external/com_google_cloud_go_longrunning/longrunning.go:60:10: cannot use inner (variable of type *"cloud.google.com/go/longrunning/autogen".OperationsClient) as type operationsClient in struct literal:
        *"cloud.google.com/go/longrunning/autogen".OperationsClient does not implement operationsClient (wrong type for CancelOperation method)
                have CancelOperation(ctx context.Context, req *longrunningpb.CancelOperationRequest, opts ...gax.CallOption) error
                want CancelOperation(context.Context, *"google.golang.org/genproto/googleapis/longrunning".CancelOperationRequest, ...gax.CallOption) error
```
Following this post: https://github.com/googleapis/google-cloud-go/issues/7233
I downgrade `longrunning` package version to v0.2.1.
But it fails for spanner for another problem.
```
external/com_google_cloud_go_spanner/protoutils.go:85:67: undefined: spanner.TypeAnnotationCode_PG_JSONB
external/com_google_cloud_go_spanner/value.go:1698:59: undefined: spanner.TypeAnnotationCode_PG_JSONB
external/com_google_cloud_go_spanner/value.go:1716:60: undefined: spanner.TypeAnnotationCode_PG_JSONB
external/com_google_cloud_go_spanner/value.go:2374:59: undefined: spanner.TypeAnnotationCode_PG_JSONB
external/com_google_cloud_go_spanner/value.go:2557:61: undefined: spanner.TypeAnnotationCode_PG_JSONB
```
Do you happen to know what's happening?

**Comment by rahul2393** [comment]
Can you help with the answers below
1) Are you using v1.41.0 when you got the initial SQL error as described in the issue description? if yes can you share the Golang snippet to replicate, the snippet which I share earlier was working fine with version 1.41.0 anyways.
2) Do you use go.mod file for dependency management, if yes can you share go.mod file where issue is happening for "bad argument".

**Comment by dentiny** [comment]
Hi @rahul2393 sorry for the confusion, I think I didn't make myself clear, and I'm using a mixed version for multiple versions of libraries.

I have some updates:
Currently I'm using
- spanner v1.43.0
- longrunning v0.3.0
- genproto v0.0.0-20230119192704-9d59e20e5cd1

The above version combination fails with
```
external/com_google_cloud_go_longrunning/longrunning.go:60:10: cannot use inner (variable of type *"cloud.google.com/go/longrunning/autogen".OperationsClient) as type operationsClient in struct literal:
        *"cloud.google.com/go/longrunning/autogen".OperationsClient does not implement operationsClient (wrong type for CancelOperation method)
                have CancelOperation(ctx context.Context, req *longrunningpb.CancelOperationRequest, opts ...gax.CallOption) error
                want CancelOperation(context.Context, *"google.golang.org/genproto/googleapis/longrunning".CancelOperationRequest, ...gax.CallOption) error
```

The issue seems to be visible in this github issue: https://github.com/googleapis/google-cloud-go/issues/7233
So I tried to downgrade longrunning to v0.2.1.
```
$ go get cloud.google.com/go/longrunning@v0.2.1
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go get: downgraded cloud.google.com/go/aiplatform v1.27.0 => v1.24.0
go get: downgraded cloud.google.com/go/bigquery v1.44.0 => v1.43.0
go get: downgraded cloud.google.com/go/compute v1.14.0 => v1.12.1
go get: downgraded cloud.google.com/go/compute/metadata v0.2.3 => v0.2.2
go get: downgraded cloud.google.com/go/datastore v1.10.0 => v1.9.0
go get: downgraded cloud.google.com/go/firestore v1.9.0 => v1.8.0
go get: downgraded cloud.google.com/go/iam v0.8.0 => v0.7.0
go get: downgraded cloud.google.com/go/logging v1.6.1 => v1.5.0
go get: downgraded cloud.google.com/go/longrunning v0.3.0 => v0.2.1
go get: downgraded cloud.google.com/go/pubsub v1.27.1 => v1.26.0
go get: downgraded cloud.google.com/go/pubsublite v1.5.0 => v1.4.1
go get: downgraded cloud.google.com/go/spanner v1.43.0 => v1.40.0
go get: downgraded google.golang.org/api v0.106.0 => v0.103.0
go get: downgraded google.golang.org/genproto v0.0.0-20230119192704-9d59e20e5cd1 => v0.0.0-20221027153422-115e99e71e1c
```
As you could see, a bunch of other related libraries get downgraded.
For now, the version for these libraries are
- spanner v1.40.0
- longrunning v0.2.1
- genproto v0.0.0-20221027153422-115e99e71e1c

The compilation fails for
```
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:282:49: undefined: database.ListDatabaseRolesRequest
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:557:86: undefined: database.ListDatabaseRolesRequest
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1181:90: undefined: database.ListDatabaseRolesRequest
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1187:38: undefined: database.ListDatabaseRolesRequest
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1188:73: undefined: database.DatabaseRole
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1189:23: undefined: database.ListDatabaseRolesResponse
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1200:38: c.databaseAdminClient.ListDatabaseRoles undefined (type "google.golang.org/genproto/googleapis/spanner/admin/database/v1".DatabaseAdminClient has no field or method ListDatabaseRoles)
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1744:25: undefined: database.DatabaseRole
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1759:76: undefined: database.DatabaseRole
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1769:53: undefined: database.DatabaseRole
external/com_google_cloud_go_spanner/admin/database/apiv1/database_admin_client.go:1200:38: too many errors
```
it leads to me this github issue: https://github.com/googleapis/google-cloud-go/issues/6632
which indicates another version mismatch.

I tried to downgrade spanner to v1.36.0, which seems to be a workable version.
The good thing is no compilation failure, but not all the functionality is supported.
```
spanner: code = "Unknown", desc = "rpc error: code = Unknown desc = selecting with more than one FROM clause not yet supported"
```
I'm wondering what are the workable version combination?

btw, I'm using bazel rather than native golong.

**Comment by rahul2393** [comment]
@dentiny Can you please pin these deps to and check 
```
spanner v1.43.0
longrunning v0.4.0
genproto v0.0.0-20230125152338-dcaf20b6aeaa

```

**Comment by rahul2393** [comment]
@dentiny I am trying to reproduce the issue here https://github.com/rahul2393/spanner-bazel if you can share your bazel/workspace file that will really help me debug the issue better.

**Comment by dentiny** [comment]
> Can you please pin these deps to corresponding versions and check again

Unfortunately I still cannot work with these version combinations. :(

**Comment by rahul2393** [comment]
@dentiny Is is possible the versions are overridden somewhere in your workspace, will it be possible for you to share MVP repro.
Did you try https://github.com/rahul2393/spanner-bazel?

**Comment by rahul2393** [comment]
Moving the priority to P3 since its not reproducible.

**Comment by rahul2393** [comment]
Please re-open if issue persist.
